version: '2.0'

services:
  web:
    image: ruby:2.3
    command: rails server -b 0.0.0.0 -p 80
    environment:
      RAILS_ENV:
      DATABASE_HOST: db
    working_dir: /app
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    tmpfs: /app/tmp
    depends_on:
      - db
    ports:
      - 80

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
  bundle:
